import Navbar from "@/components/Navbar";
import { bitcount } from "@/lib/fonts";
import ReactQueryProvider from "@/providers/ReactQueryProviders";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bounce, ToastContainer } from "react-toastify";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 2. Tambahkan variabel font Anda di sini */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bitcount.variable}`}
      >
        <Navbar />
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
          transition={Bounce}
        />
      </body>
    </html>
  );
}
